#!/bin/bash
#:Usage: brew purge formula
#:
#:Removes the package and all dependancies.
#:
# install it with the following command
# sudo install brew-purge /usr/local/bin
# run it
# brew purge package
PKG="$1"
if [ -z "$PKG" ];then
   brew purge --help
   exit 1
fi
brew rm $PKG
[ $? -ne 0 ] && exit 1
while brew rm $(join <(brew leaves) <(brew deps $PKG)) 2>/dev/null
  do :
done
echo Package $PKG and its dependancies have been removed.
exit 0
